redis:
  image: wlan0/redis
  privileged: true
  environment:
      VOL_NAME: ${VOL_NAME}
  labels:
          io.rancher.scheduler.global: 'true'
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib:/usr/lib
      - /lib:/lib 
  commmand: ["/run-redis.sh"]
