rexray:
    image: wlan0/sdc
    stdin_open: true
    tty: true
    privileged: true
    environment:
        STACK_NAME: ${SCALEIO_STACK_NAME}
    volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /dev:/dev
        - /lib/modules:/lib/modules
        - /run/docker/plugins:/run/docker/plugins
        - /var:/var:shared
    labels:
        io.rancher.container.pull_image: always
