rexray:
  image: wlan0/rexray
  pid: host
  privileged: true
  environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      SCALEIO_ENDPOINT: ${SCALEIO_ENDPOINT}
      SCALEIO_INSECURE: ${SCALEIO_INSECURE}
      SCALEIO_MDM_USERNAME: ${SCALEIO_MDM_USERNAME}
      SCALEIO_MDM_PASS: ${SCALEIO_MDM_PASS}
      SCALEIO_MDM_SYSTEM_ID: ${SCALEIO_MDM_SYSTEM_ID}
      SCALEIO_PROT_DOMAIN: ${SCALEIO_PROT_DOMAIN}
      SCALEIO_STORAGE_POOL: ${SCALEIO_STORAGE_POOL}
      SCALEIO_THIN_OR_THICK_PROVISION: ${SCALEIO_THIN_OR_THICK_PROVISION}
      RACKSPACE_IDENTITY_URL: ${RACKSPACE_IDENTITY_URL}
      RACKSPACE_USERNAME: ${RACKSPACE_USERNAME}
      RACKSPACE_PASS: ${RACKSPACE_PASS}
      RACKSPACE_TENANT_NAME: ${RACKSPACE_TENANT_NAME}
      RACKSPACE_REGION: ${RACKSPACE_REGION}
  volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /var:/var:shared
      - /etc:/etc
      - /dev:/dev
      - /opt/emc:/opt/emc
      - /bin/emc:/bin/emc
  labels:
    io.rancher.scheduler.global: 'true'
  command: ["rexray", "start", "-f"]
